spring:
    datasource:
        url: jdbc:mysql://192.168.56.101:6603/test
        username: root
        password: rootpasswd
        driverClass: com.mysql.cj.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
        hiebernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect